name: Node.js CI/CD

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Start application
        run: |
          node index.js &
          sleep 3

      - name: Check application
        run: curl http://localhost:3000

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1
          role-session-name: GitHubActions-${{ github.run_id }}

      - name: Check AWS identity
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/node-ci-cd-ecr:${{ github.sha }} \
            -t ${{ steps.login-ecr.outputs.registry }}/node-ci-cd-ecr:latest \
            .

      - name: Push Docker image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/node-ci-cd-ecr:${{ github.sha }}

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/node-ci-cd-ecr:latest
