name: Node.js CI/CD

on:
  push:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Get source code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Start application
      - name: Start application
        run: |
          node index.js &
          sleep 3

      # 5. Test application
      - name: Check application
        run: curl http://localhost:3000

      # 6. Configure AWS using OIDC
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      # 7. Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # 8. Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/node-ci-cd-ecr:${{ github.sha }} \
            -t ${{ steps.login-ecr.outputs.registry }}/node-ci-cd-ecr:latest \
            .

      # 9. Push image to ECR
      - name: Push Docker image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/node-ci-cd-ecr:${{ github.sha }}

          docker push \
            ${{ steps.login-ecr.outputs.registry }}/node-ci-cd-ecr:latest
